### ISSUE TITLE
Markdown looses formatting

### ISSUE THREAD

**Issue by xypnox** [karuna/tera-vscode#19]
While using the extension, tera affects the markdown syntax highlighting, making it unusable in a project with both tera and markdown files.

Reference: https://i.imgur.com/BUldL1d.mp4

**Comment by cdmistman** [comment]
I also encountered this bug, it's been driving me mad until now

**Comment by karuna** [comment]
I'll check it tonight

**Comment by karuna** [comment]
pushed v0.0.9, sorry about that :bow:

**Comment by xypnox** [comment]
Works nicely on v0.0.9, thanks a lot!
