### ISSUE TITLE
Format on save indents by four tabs

### ISSUE THREAD

**Issue by Azorlogh** [karuna/tera-vscode#4]
I have the "format on save" option activated, and my indent style set as tabs.
When I save, everything gets indented by _four tabs_ instead of one.

The behavior is actually really weird, see:
https://gfycat.com/crazylastinglhasaapso

Additional info: I'm on Arch 5.8.13, and using the Microsoft branded release

**Comment by karuna** [comment]
I'll check that later

**Comment by Azorlogh** [comment]
It seems to be fixed, i think it may have been a conflict with another extension, or I messed up my formatter somehow
