### ISSUE TITLE
Is it possible to turn formatting feature off?

### ISSUE THREAD

**Issue by itsfarseen** [karuna/tera-vscode#5]
Before formatting:
![image](https://user-images.githubusercontent.com/40014472/98653944-a9a79a00-2363-11eb-88d1-0b54629c8d1c.png)

After formatting:
![image](https://user-images.githubusercontent.com/40014472/98653962-b0361180-2363-11eb-8348-446ccdbadd84.png)

I prefer the before version. Any way to disable formatting, without disabling `formatOnSave` globally?

**Comment by karuna** [comment]
let me check

**Comment by pyrrho** [comment]
You can set `formatOnSave` for just the Tera language with the below,
```
  "[tera]": {
    "editor.formatOnSave": false
  }
```

I'm curious if the formatting engine that's being used could be configured (for example, allowing empty lines as per happycoder's before image above)?

**Comment by gatewaynode** [comment]
^^^ This works, exposing this in the config UI would be useful.  I also noticed it adding unnecessary closing tags and performing inconsistent attribute reordering.

**Comment by karuna** [comment]
I think it works now as of 0.0.7
