### ISSUE TITLE
A question and a request: using the Tera plugin with HTML auto-indentation rules

### ISSUE THREAD

**Issue by xpe** [karuna/tera-vscode#9]
I use Zola (and thus Tera) with VS Code. Thank you for this plugin!

First, a question. Is the intended design for this plugin to do some syntax highlighting and "delegate" additional syntax highlighting to other active plugins (such as HTML)? I ask because I have not dug into VS Code plugins. But this reminds me of the major/minor mode distinction in Emacs.

Second, a specific request. I like the usual VS Code auto-indentation rules when editing HTML files. However, these don't work after I set a file's language mode to Tera. Is there a setting for this that I overlooked? What do you recommend?

**Comment by xpe** [comment]
I'm wondering  if would it be useful to create a "Tera-HTML" language mode?

**Comment by karuna** [comment]
It was originally just for syntax highlighting, but there's this https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages

The HTML integration is not very good at the moment, I just don't have time to check it.

**Comment by xpe** [comment]
Thanks for the pointer to embedded languages in VS Code!

**Comment by karamfd** [comment]
> It was originally just for syntax highlighting, but there's this https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages
> 
> The HTML integration is not very good at the moment, I just don't have time to check it.

I forked the repo and added the HTML integration functionality that was requested by @xpe.

That being said, the .tera extension is no longer needed. When you create an HTML file inside of a template directory for example, it will be displayed as HTML instead of Tera Template. 

This also addresses issues #5 and #6. Formatter is not needed since we can use the built-in HTML formatter in VSCode or another formatter like Prettier for example. Snippets also work in HTML 😃

**Comment by JoshLambda** [comment]
> That being said, the .tera extension is no longer needed. When you create an HTML file inside of a template directory for example, it will be displayed as HTML instead of Tera Template.

.tera extension is still needed by some web frameworks like [Rocket](https://github.com/SergioBenitez/Rocket) though.

**Comment by karuna** [comment]
@JoshLambda can you associate .tera as html in vscode?

**Comment by JoshLambda** [comment]
Yes, it works. Thanks for the suggestion.

For the record, either:

`<Click on language name, located on the status bar> -> "Configure File Association for '.tera'..." -> "HTML"`

or add the following to vscode settings file:

```
    "files.associations": {
        "*.tera": "html"
    },
```

**Comment by karuna** [comment]
I think it works now as of 0.0.7
